defaults:
  - data: cifar10
  - model: resnet
  - logging: wandb
  - _self_

seed: 42
device: "cuda"
num_classes: 10
amp: true
deterministic: false
print_freq: 50
save_best: true
output_dir: ${hydra:runtime.output_dir}

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${hydra.job.name}_seed${seed}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
